name: geeta_furniture
description: Geeta Ply & Furniture
publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  url_launcher: ^6.2.6
  share_plus: ^7.2.1
  app_links: ^6.3.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  cloud_firestore: ^5.6.12
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  http: ^1.2.0


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


